import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const { result, content, type, format = "markdown" } = await req.json();

    if (!result) {
      return NextResponse.json({ error: "No analysis result provided" }, { status: 400 });
    }

    const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const contentType = type === "tweet" ? "X/Twitter Post" : "Substack Article";

    if (format === "markdown") {
      const md = `# ContentLens Analysis Report
**Date:** ${date}
**Content Type:** ${contentType}

---

## Overall Score: ${result.overallScore}/100

${result.summary}

---

## 🎣 Hook Strength — ${result.hookStrength.score}/100

${result.hookStrength.feedback}

## 🏗️ Structure & Readability — ${result.structure.score}/100

${result.structure.feedback}

## 💡 Emotional Triggers — ${result.emotionalTriggers.score}/100

${result.emotionalTriggers.feedback}

**Triggers detected:** ${(result.emotionalTriggers.triggers || []).join(", ")}

---

## 🚀 How to Improve

${(result.improvements || []).map((imp: string, i: number) => `${i + 1}. ${imp}`).join("\n")}

---

## Original Content

> ${(content || "").split("\n").join("\n> ")}

---

*Generated by ContentLens — AI-Powered Content Analysis*
`;

      return new NextResponse(md, {
        headers: {
          "Content-Type": "text/markdown; charset=utf-8",
          "Content-Disposition": `attachment; filename="contentlens-report-${Date.now()}.md"`,
        },
      });
    }

    // CSV format
    const csv = `Metric,Score,Feedback
Overall,${result.overallScore},"${result.summary.replace(/"/g, '""')}"
Hook Strength,${result.hookStrength.score},"${result.hookStrength.feedback.replace(/"/g, '""')}"
Structure,${result.structure.score},"${result.structure.feedback.replace(/"/g, '""')}"
Emotional Triggers,${result.emotionalTriggers.score},"${result.emotionalTriggers.feedback.replace(/"/g, '""')}"
`;

    return new NextResponse(csv, {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="contentlens-report-${Date.now()}.csv"`,
      },
    });
  } catch {
    return NextResponse.json({ error: "Export failed" }, { status: 500 });
  }
}
